name: Despliegue Naval CNCS

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Extraer Planos
        uses: actions/checkout@v4
      - name: Configurar Astillero
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Ensamblar Tropas y Motor
        run: npm install
      - name: Construir Centro de Mando
        run: npx vite build
      - name: Preparar Enlace
        uses: actions/configure-pages@v4
      - name: Subir Nave Terminada
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'
      - name: Desplegar a Produccion
        id: deployment
        uses: actions/deploy-pages@v4
